### ISSUE TITLE
Exosome model is missing starting model coordinates for Rrp46_gfp-m2

### ISSUE THREAD

**Issue by benmwebb** [ihmwg/IHM-dictionary#49]
We refer to a starting model `Rrp46_gfp-m2` in the `.cif` file for the Exosome example but don't have any coordinates for it in `ihm_starting_model_coord`. This is probably because the residue numbers are offset between the starting model and the output IMP model, and the IMP code is confused somehow. Will investigate.

**Comment by benmwebb** [comment]
Out of curiosity, why doesn't the mmCIF validator complain about this?

**Comment by brindakv** [comment]
Some of the starting models, localization densities and output models are not aligned when visualizing with ChimeraX.

**Comment by tomgoddard** [comment]
The ChimeraX log says it failed to align Ski7_3izq_modeller_vmd.pdb chain X starting model to the sphere models.  That is the only obvious alignment issue I see with the exosome.cif example.  The reason for that is that the exosome example has 2 states, Rrp6 and Ski7 and the unaligned starting model is only part of the Ski7 state.  But ChimeraX is only trying to align it to the Rrp6 state output models.  The reason for that is that ChimeraX shows just the first output model group.  There are 4 groups in the exosome case, the first 2 or two clusters of Rrp6 and the second 2 are two clusters of Ski7.  So ChimeraX is initially showing only the Rrp6 output model for cluster 1.  But it tries to align all starting models to that output model, and it can't align the Ski7_3izq... starting model since it is not part of that state.  The sensible behavior would be to hide that starting model.  I'll make a ticket for that.  Another issue is that there is only one copy of the starting models in ChimeraX, so if you switch to showing one of the other 4 output models, the starting models are no longer correctly aligned with those.  There is currently no capability to realign the starting models to a different output model.  I'll make a ticket for that too.

**Comment by benmwebb** [comment]
Closing as this is better handled now by #52 and #53.
