### ISSUE TITLE
Add pseudo-atoms support to define restraints

### ISSUE THREAD

**Issue by mtrellet** [ihmwg/IHM-dictionary#73]
In some of HADDOCK protocols, we make use of pseudo-atoms to define distance restraints between either other pseudo-atoms matching geometrical features of a molecule (center of mass for instance) or atom/residues of the molecular partners.

This is, for instance, the case in the HADDOCK-EM protocol at the rigid-body minimization stage (it0) as described below.

<img width="1327" alt="screen shot 2018-09-17 at 16 19 51" src="https://user-images.githubusercontent.com/715654/46616051-021f6400-cb1a-11e8-8430-c95734dc9cfb.png">

If part of the definition of pseudo-atoms is made within the protocol and then does not mandatorily require to be present in a mmCIF file, the centroid coordinates used in the HADDOCK-EM protocol, and obtained via a fitting of the molecular structures in a density map, are provided as input by the users. For the sake of exhaustiveness, it would be interesting to be able to add them in the IHM dictionary and be able to list them in the `poly_atom_feature` section to be further referenced in `derived_distance_restraints`.

**Comment by brindakv** [comment]
@benmwebb, @mtrellet, based on today's discussion, I added a new data category (`IHM_FEATURE_PSEUDO_SITE`) to address this issue. Please test to make sure it resolves the issue.

**Comment by benmwebb** [comment]
@brindakv Would a feature that selects a pseudo site use `ihm_feature_list.feature_type` = `atom` ? Or should `feature_type` be extended? `atom` is described as "an atom or a set of atoms from a polymeric or non-polymeric entity" which doesn't sound quite right to me since a) a pseudo site isn't really an 'atom', b) since `ihm_feature_pseudo_site` uses `feature_id` as the key there can only be a single pseudo site in a feature (not a set of them) and c) the pseudo site is just a point, so isn't associated with an entity, polymeric or otherwise. Or am I misreading the dictionary here?

**Comment by brindakv** [comment]
@benmwebb, I addressed this issue in the recent update.

**Comment by benmwebb** [comment]
python-ihm should support pseudo sites as of ihmwg/python-ihm@6cec1809.
