### ISSUE TITLE
Identify models belonging to a collection

### ISSUE THREAD

**Issue by brindakv** [ihmwg/IHM-dictionary#83]
Create data items / categories to identify models that belong to a collection.

There are two options: 
 - ModelCIF uses `_entry.ma_collection_id`: This allows to identify the collection from the entry; the reverse is facilitated implicitly by embedding the `collection_id` within the `_entry.id`
 - PDBx/mmCIF uses [pdbx_deposit_group](https://mmcif.wwpdb.org/dictionaries/mmcif_pdbx_v50.dic/Categories/pdbx_deposit_group.html): This allows to identify the collection from the entry; but the reverse will require parsing all entries to find the respective deposit groups that entries belong to. 
   - [pdbx_database_related](https://mmcif.wwpdb.org/dictionaries/mmcif_pdbx_v50.dic/Categories/pdbx_database_related.html) can be used to identify entries in a collection, but this would require duplication of information in all entries in the collection.  
 - [pdbx_investigation](https://mmcif.wwpdb.org/dictionaries/mmcif_pdbx_v50.dic/Categories/pdbx_investigation.html): This allows for a broader set of related data from external and internal resources. 
 - Consider having a supplementary file with details about entries within a collection.

**Comment by brindakv** [comment]
Proposal: 
- Create `ihm_entry_collection` data category with the following data items (to be populated in the entry mmCIF file and the supplementary collection file)
  - `_ihm_entry_collection.collection_id`
  - `_ihm_entry_collection.name`
  - `_ihm_entry_collection.details`
- Create `ihm_entry_collection_mapping` data category with the following data items (to be populated in the supplementary collection file)
  - `_ihm_entry_collection_mapping.ordinal_id`
  - `_ihm_entry_collection_mapping.entry_id`
  - `_ihm_entry_collection_mapping.collection_id`
- Create `ihm_entry_collection_associated_files` data category with the following data items (to be populated in the entry mmCIF file)
  - `_ihm_entry_collection_associated_files.id`
  - `_ihm_entry_collection_associated_files.collection_id`
  - `_ihm_entry_collection_associated_files.file_url`
  - `_ihm_entry_collection_associated_files.file_type`
  - `_ihm_entry_collection_associated_files.file_format`
  - `_ihm_entry_collection_associated_files.file_content`
  - `_ihm_entry_collection_associated_files.details`

**Comment by benmwebb** [comment]
This seems reasonable to me. I guess the important point is whether collections are managed by PDB(-Dev) or by individual contributors.

If managed by PDB or PDB-Dev, you can ensure that `collection_id` is unique and that the collection file is well-formed (I assume there would be a mini-dictionary to describe this file). And you wouldn't need the `_ihm_entry_collection_associated_files` table; the `collection_id` would be enough, just as a PDB ID is today. But that does introduce a maintenance overhead for PDB.

If managed by individual contributors, how would you ensure that `collection_id` is unique? Or that the collection file is well-formed? I'm wary of using a URL here since URLs break all the time. But I guess we can't use a DOI since DOI contents are (supposed to be) immutable, so you'd need to issue a new DOI whenever a new entry is added to the collection.

**Comment by brindakv** [comment]
Sorry for not clarifying. The collections will be managed by the archive. It does create an overhead, but that is the only way to ensure that the `collection_ids` are unique and consistent. 

Why would you not need the `ihm_entry_collection_associated_files` table? From an entry you will need to find the `collection_id` and the location of the supplementary file corresponding to the `collection_id` to find other entries belonging to the collection. Perhaps we don't all those data items in that table, but I don't see how we can do away with the entire table.

**Comment by benmwebb** [comment]
> Why would you not need the `ihm_entry_collection_associated_files` table?

You have the `collection_id` from the `ihm_entry_collection` table. Since it's unique and managed by the archive, isn't that all you need to look up the collection file, just like any other accession? You don't need a URL or type/format/content to look up a PDB file given an ID after all - you just need `1NSO` in the file, not `https://files.rcsb.org/download/1NSO.pdb`.

**Comment by brindakv** [comment]
@benmwebb I see your point. Not defining `ihm_entry_collection_associated_files` table would make filename and location implicit. Is that ok? In addition, should we allow an entry to belong to multiple collections (not just based on deposition / primary citation)?

**Comment by benmwebb** [comment]
> Not defining `ihm_entry_collection_associated_files` table would make filename and location implicit. Is that ok?

I think so. This would also mean you wouldn't have to change every file if the URLs change (e.g. if PDB-Dev were folded into PDB) and the collection file could be available from multiple locations (e.g. PDBe, PDBj).

> should we allow an entry to belong to multiple collections

Seems reasonable to me.

**Comment by brindakv** [comment]
Addressed in v1.18.
