### ISSUE TITLE
Make a multistate example

### ISSUE THREAD

**Issue by tomgoddard** [ihmwg/IHM-dictionary#9]
The current nup84, mediator and exosome IHM data examples are not multistate, so the multistate features of the format have not been tested.

Ben and Brinda and I discussed making multistate example.  Ben said the exosome project was 2 states but done as 2 separate imp jobs for the two states so it is not an ideal example.  Another multistate system Ben mentioned was published years ago and does not use current IMP protocols which would make it hard to put into IHM format.  So we didn't come up with any candidate example systems.

**Comment by benmwebb** [comment]
PMI as of salilab/pmi@8ec5930 should have basic support for multi-state modeling. I've generated a preliminary version of the exosome example including the two states that were originally modeled, available at `ftp://salilab.org/ben/exosome/multi_state/exosome.cif`. Please check it out when you have time and let me know if a) it conforms to the dictionary and b) it makes sense conceptually to you. I think it should be complete (with the exception of full details for the Ski7 comparative model, see integrativemodeling/exosome#4).

Note that the two states, since they share a common exo10 core, use the same set of asym_ids for exo10 in each state (only the asym_ids for the components that differ in the two states are unique). Each state is a separate subassembly. The crosslinking data was collected for both states simultaneously and so should not contain any duplicates.

I expect the file will need a bit of tweaking. When it looks good to everyone, I'll update the exosome example in the repository.
